@WebBoardGames.API_HostAddress = http://localhost:5008

GET {{WebBoardGames.API_HostAddress}}/todos/
Accept: application/json

###

GET {{WebBoardGames.API_HostAddress}}/todos/1
Accept: application/json

###
